theme: jekyll-theme-researcher

title: Dr. Konstantin Selyunin

description: Personal website of Dr. Konstantin Selyunin

markdown: kramdown

footer: yes
footer_url: "https://github.com/selyunin"
footer_text: "2023, Dr. Konstantin Selyunin"

favicon: yes
favicon_location: /img/favicon.ico

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag

include:
  - _pages

exclude:
  - README.md

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about/"
 - name: "Videos"
   link: "/videos/"
 - name: "Tech posts"
   link: "/tech-posts/"
 - name: "Publications"
   link: "/publications/"
 - name: "Running"
   link: "/running/"
 - name: "Music"
   link: "/music/"
 - name: "Contact"
   link: "/contact/"